# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0002_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_logo',
        ),
    ]
