# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0004_auto_20170923_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture_id', models.IntegerField()),
                ('fixture_ht_score', models.CharField(max_length=5)),
                ('fixture_ft_score', models.CharField(max_length=5)),
                ('fixture_gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Statistics.Gameweek')),
                ('fixture_team_away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Away_Team', to='Statistics.Team')),
                ('fixture_team_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Home_Team', to='Statistics.Team')),
                ('fixture_venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Statistics.Venue')),
            ],
        ),
    ]
