# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0005_fixture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='fixture_ft_score',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='fixture_ht_score',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
