# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0006_auto_20170923_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='fixture_start',
            field=models.DateTimeField(default='2017-09-30 14:00:00'),
            preserve_default=False,
        ),
    ]
