# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0008_fixture_team_stat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fixture_Team_Stat',
            new_name='FixtureTeamStat',
        ),
    ]
