# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0009_auto_20170925_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixtureteamstat',
            name='fts_corners',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixtureteamstat',
            name='fts_fouls_committed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixtureteamstat',
            name='fts_fouls_drawn',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixtureteamstat',
            name='fts_goalkicks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixtureteamstat',
            name='fts_offsides',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixtureteamstat',
            name='fts_passes_accuracy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixtureteamstat',
            name='fts_passes_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixtureteamstat',
            name='fts_possession',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixtureteamstat',
            name='fts_redcards',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixtureteamstat',
            name='fts_saves',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixtureteamstat',
            name='fts_shots_blocked',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixtureteamstat',
            name='fts_shots_insidebox',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixtureteamstat',
            name='fts_shots_offtarget',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixtureteamstat',
            name='fts_shots_ontarget',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixtureteamstat',
            name='fts_shots_outsidebox',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixtureteamstat',
            name='fts_shots_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixtureteamstat',
            name='fts_substitutions',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixtureteamstat',
            name='fts_yellowcards',
            field=models.IntegerField(null=True),
        ),
    ]
