# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0010_auto_20171009_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('player_name', models.CharField(max_length=50)),
                ('player_nationality', models.CharField(max_length=15)),
                ('player_height', models.CharField(max_length=10)),
                ('player_weight', models.CharField(max_length=10)),
                ('player_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Player_Team', to='Statistics.Team')),
            ],
        ),
    ]
