# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0011_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_height',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_weight',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
