# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0012_auto_20171010_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_common_name',
            field=models.CharField(default='Something', max_length=50),
            preserve_default=False,
        ),
    ]
