# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0013_player_player_common_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_id', models.IntegerField()),
                ('goal_minute', models.IntegerField(null=True)),
                ('goal_type', models.CharField(max_length=10)),
                ('goal_assist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Goal_Assist', to='Statistics.Player')),
                ('goal_fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Goal_Fixture', to='Statistics.Fixture')),
                ('goal_scorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Goal_Scorer', to='Statistics.Player')),
                ('goal_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Goal_Team', to='Statistics.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_id', models.IntegerField()),
                ('sub_time', models.IntegerField()),
                ('sub_fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sub_Fixture', to='Statistics.Fixture')),
                ('sub_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sub_In', to='Statistics.Player')),
                ('sub_out', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sub_Out', to='Statistics.Player')),
                ('sub_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sub_Team', to='Statistics.Team')),
            ],
        ),
    ]
