# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0014_goal_substitution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substitution',
            name='sub_id',
            field=models.IntegerField(null=True),
        ),
    ]
