# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0016_auto_20171010_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixturePlayerStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fps_start', models.BooleanField()),
                ('fps_formation_position', models.IntegerField(null=True)),
                ('fps_position', models.CharField(max_length=5)),
                ('fps_yellowcards', models.IntegerField(null=True)),
                ('fps_redcards', models.IntegerField(null=True)),
                ('fps_fouls_committed', models.IntegerField(null=True)),
                ('fps_fouls_drawn', models.IntegerField(null=True)),
                ('fps_goal_scored', models.IntegerField(null=True)),
                ('fps_goal_conceded', models.IntegerField(null=True)),
                ('fps_assists', models.IntegerField(null=True)),
                ('fps_blocks', models.IntegerField(null=True)),
                ('fps_clearances', models.IntegerField(null=True)),
                ('fps_minutes_played', models.IntegerField(null=True)),
                ('fps_offsides', models.IntegerField(null=True)),
                ('fps_pen_missed', models.IntegerField(null=True)),
                ('fps_pen_scored', models.IntegerField(null=True)),
                ('fps_pen_saved', models.IntegerField(null=True)),
                ('fps_saves', models.IntegerField(null=True)),
                ('fps_tackles', models.IntegerField(null=True)),
                ('fps_passes_total', models.IntegerField(null=True)),
                ('fps_passes_accuracy', models.IntegerField(null=True)),
                ('fps_cross_total', models.IntegerField(null=True)),
                ('fps_shots_total', models.IntegerField(null=True)),
                ('fps_shots_ontarget', models.IntegerField(null=True)),
                ('fps_shots_offtarget', models.IntegerField(null=True)),
                ('fps_fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fixture_Player_Stats', to='Statistics.Fixture')),
                ('fps_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stat_Player', to='Statistics.Player')),
                ('fps_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Player_Team_Stat', to='Statistics.Team')),
            ],
        ),
    ]
