# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0017_fixtureplayerstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixtureplayerstat',
            name='fps_interceptions',
            field=models.IntegerField(null=True),
        ),
    ]
