# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0018_fixtureplayerstat_fps_interceptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_common_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_nationality',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
