# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0019_auto_20171011_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(null=True),
        ),
    ]
