# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0021_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='fixture_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixtureteamstat',
            name='fts_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gameweek',
            name='gw_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gameweek',
            name='gw_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='season_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_id',
            field=models.IntegerField(null=True),
        ),
    ]
